### ISSUE TITLE
Breakage when source profile absent from ini file

### ISSUE THREAD

**Issue by vancluever** [vancluever/aws-runas#1]
Needs to be fixed to handle profiles without source_profile for credentials (will probably come up with using the tool with instance profiles and what not as well).

```
/Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.1/lib/aws_runas/config.rb:54:in `load_source_profile': undefined local variable or method `profile' for #<AwsRunAs::Config:0x007fee340887a0> (NameError)
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.1/lib/aws_runas/main.rb:37:in `sts_client'
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.1/lib/aws_runas/main.rb:47:in `assume_role'
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.1/lib/aws_runas/cli.rb:51:in `start'
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.1/exe/aws-runas:19:in `<top (required)>'
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/bin/aws-runas:23:in `load'
	from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/bin/aws-runas:23:in `<main>'
```

**Comment by vancluever** [comment]
Should be resolved by 0.1.2.
