### ISSUE TITLE
Error handling for unknown profile

### ISSUE THREAD

**Issue by vancluever** [vancluever/aws-runas#3]
Using an incorrect profile gives a misleading error message, probably because the variable was returned as nil:

```
 /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/param_validator.rb:26:in `validate!': missing required parameter params[:role_arn] (ArgumentError)
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/seahorse/client/request.rb:70:in `send_request'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws_runas-0.1.2/lib/aws_runas/main.rb:46:in `new'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws_runas-0.1.2/lib/aws_runas/main.rb:46:in `assume_role'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws_runas-0.1.2/lib/aws_runas/cli.rb:51:in `start'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/gems/aws_runas-0.1.2/exe/aws-runas:19:in `<top (required)>'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/bin/aws-runas:23:in `load'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/bin/aws-runas:23:in `<main>'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
[15:33:54][Step 2/2] 	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vancluever** [comment]
Should be fixed in 0.1.3.
