### ISSUE TITLE
Running with no params should give help and bail

### ISSUE THREAD

**Issue by vancluever** [vancluever/aws-runas#4]
Right now it does not ;)

```
/Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/param_validator.rb:26:in `validate!': missing required parameter params[:role_arn] (ArgumentError)
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/request.rb:70:in `send_request'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.3/lib/aws_runas/main.rb:46:in `new'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.3/lib/aws_runas/main.rb:46:in `assume_role'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.3/lib/aws_runas/cli.rb:51:in `start'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/gems/aws_runas-0.1.3/exe/aws-runas:19:in `<top (required)>'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/bin/aws-runas:23:in `load'
    from /Users/cmarchesi/.chefdk/gem/ruby/2.1.0/bin/aws-runas:23:in `<main>'
```

**Comment by vancluever** [comment]
Closing this. Don't want this anyway - there is some intended behaviour here where running with no parameters can possibly load a default profile with that has a role ARN.
